/**
 * Medical Document Page Classifier - Node.js Implementation v2.0
 *
 * Estratégia 100% Node.js (sem binários do sistema):
 * - PDFs com texto nativo: extração direta com pdfjs-dist por página
 * - PDFs escaneados: renderização com pdfjs-dist + @napi-rs/canvas, OCR via LLM
 * - JPEG/JPG: LLM vision diretamente
 * - Compatível com produção (sem poppler-utils, ghostscript, etc.)
 */

import * as pdfParseModule from "pdf-parse";
const pdfParse = (pdfParseModule as any).default ?? pdfParseModule;

import sharp from "sharp";
import { createCanvas } from "@napi-rs/canvas";
import * as fs from "fs";
import * as path from "path";
import { invokeLLM } from "./_core/llm";

// ─── Types ───────────────────────────────────────────────────────────────────

export type PageClassification = "laudo" | "imagem" | "indefinido";

export interface PageAnalysis {
  pageNumber: number;
  classification: PageClassification;
  score: number;
  thumbnailBase64: string;
  details: {
    wordCount?: number;
    keywordsFound?: number;
    hasNativeText?: boolean;
    isScanned?: boolean;
  };
}

export interface AnalyzeResult {
  totalPages: number;
  pages: PageAnalysis[];
}

export interface OcrPage {
  pageNumber: number;
  text: string;
  charCount: number;
}

export interface OcrResult {
  pages: OcrPage[];
}

// ─── Medical Keywords ────────────────────────────────────────────────────────

const MEDICAL_KEYWORDS = [
  "paciente", "nome", "data", "exame", "laudo", "resultado", "conclusão",
  "achados", "diagnóstico", "médico", "crm", "hospital", "clínica",
  "laboratório", "hemograma", "tomografia", "ultrassom", "ressonância",
  "radiografia", "dosagem", "valor", "referência", "normal", "alterado",
  "positivo", "negativo", "ausente", "presente", "observação",
  "impressão", "descrição", "técnica", "indicação", "solicitante",
  "assinatura", "carimbo", "registro", "prontuário", "cpf", "rg",
  "idade", "sexo", "masculino", "feminino", "nascimento",
  "mg/dl", "g/dl", "u/l", "mm/h", "mmhg", "ml", "mg", "kg",
  "hemácia", "leucócito", "plaqueta", "glicose", "creatinina",
  "colesterol", "triglicérides", "proteína", "bilirrubina",
  "tsh", "t4", "psa", "pcr", "vhs", "hba1c", "interpretação",
  "informação clínica", "técnica do exame", "impressão diagnóstica",
  "relatório", "nasc", "realizante", "pi-rads",
];

// ─── PDF Rendering (pdfjs-dist + @napi-rs/canvas — 100% Node.js) ─────────────

/**
 * Render a single PDF page to JPEG buffer using pdfjs-dist + @napi-rs/canvas.
 * 100% Node.js — sem dependência de pdftoppm, ghostscript ou qualquer binário do sistema.
 * Funciona em produção (Manus hosting) e em desenvolvimento.
 */
async function renderPdfPageToJpeg(
  pdfBuffer: Buffer,
  pageNumber: number
): Promise<Buffer | null> {
  try {
    const pdfjsLib = await import("pdfjs-dist/legacy/build/pdf.mjs");
    const uint8 = new Uint8Array(pdfBuffer);
    const loadingTask = pdfjsLib.getDocument({ data: uint8, verbosity: 0 });
    const pdf = await loadingTask.promise;

    if (pageNumber < 1 || pageNumber > pdf.numPages) return null;

    const page = await pdf.getPage(pageNumber);
    // Scale 2.0 ≈ 144 DPI for A4 — gives ~1684x2384px, good quality for OCR
    const viewport = page.getViewport({ scale: 2.0 });
    const canvasWidth = Math.round(viewport.width);
    const canvasHeight = Math.round(viewport.height);

    const canvas = createCanvas(canvasWidth, canvasHeight);
    const ctx = canvas.getContext("2d") as any;

    // White background
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, canvasWidth, canvasHeight);

    await page.render({ canvasContext: ctx, canvas: canvas as any, viewport }).promise;

    const jpegBuffer = canvas.toBuffer("image/jpeg", 90);
    return jpegBuffer as unknown as Buffer;
  } catch (err) {
    console.error(`[classifier] renderPdfPageToJpeg (pdfjs+canvas) error (page ${pageNumber}):`, err);
    return null;
  }
}

/**
 * Get number of pages in a PDF buffer using pdfjs-dist.
 */
async function getPdfPageCount(pdfBuffer: Buffer): Promise<number> {
  try {
    const pdfjsLib = await import("pdfjs-dist/legacy/build/pdf.mjs");
    const uint8 = new Uint8Array(pdfBuffer);
    const loadingTask = pdfjsLib.getDocument({ data: uint8, verbosity: 0 });
    const pdf = await loadingTask.promise;
    return pdf.numPages;
  } catch {
    try {
      const data = await pdfParse(pdfBuffer);
      return data.numpages || 1;
    } catch {
      return 1;
    }
  }
}

// ─── Text Extraction ─────────────────────────────────────────────────────────

/**
 * Extract native text from PDF per page using pdfjs-dist.
 * More reliable than pdf-parse pagerender for PDFs generated by iTextSharp, Zenite, etc.
 */
async function extractNativeTextPerPage(pdfBuffer: Buffer): Promise<string[]> {
  const pageTexts: string[] = [];
  try {
    const pdfjsLib = await import("pdfjs-dist/legacy/build/pdf.mjs");
    const uint8 = new Uint8Array(pdfBuffer);
    const loadingTask = pdfjsLib.getDocument({ data: uint8, verbosity: 0 });
    const pdf = await loadingTask.promise;

    for (let i = 1; i <= pdf.numPages; i++) {
      try {
        const page = await pdf.getPage(i);
        const textContent = await page.getTextContent();
        const text = textContent.items
          .map((item: any) => item.str)
          .join(" ")
          .trim();
        pageTexts[i - 1] = text;
      } catch {
        pageTexts[i - 1] = "";
      }
    }
  } catch (err) {
    console.error("[classifier] extractNativeTextPerPage error:", err);
    // Fallback: use pdf-parse for total text, split evenly
    try {
      const data = await pdfParse(pdfBuffer);
      const numPages = data.numpages || 1;
      const chunkSize = Math.ceil(data.text.length / numPages);
      for (let i = 0; i < numPages; i++) {
        pageTexts[i] = data.text.substring(i * chunkSize, (i + 1) * chunkSize);
      }
    } catch {
      pageTexts[0] = "";
    }
  }
  return pageTexts;
}

/**
 * Extract native text from a SINGLE PDF page using pdfjs-dist.
 * 100% Node.js — substitui pdftotext (poppler) que não está disponível em produção.
 */
async function extractNativeTextSinglePage(pdfBuffer: Buffer, pageNumber: number): Promise<string> {
  try {
    const pdfjsLib = await import("pdfjs-dist/legacy/build/pdf.mjs");
    const uint8 = new Uint8Array(pdfBuffer);
    const loadingTask = pdfjsLib.getDocument({ data: uint8, verbosity: 0 });
    const pdf = await loadingTask.promise;

    if (pageNumber < 1 || pageNumber > pdf.numPages) return "";

    const page = await pdf.getPage(pageNumber);
    const textContent = await page.getTextContent();
    const text = textContent.items
      .map((item: any) => item.str)
      .join(" ")
      .trim();
    return text;
  } catch (err) {
    console.error(`[classifier] extractNativeTextSinglePage (pdfjs) page ${pageNumber} error:`, err);
    return "";
  }
}

// ─── Scoring ─────────────────────────────────────────────────────────────────

function scoreText(text: string): { score: number; wordCount: number; keywordsFound: number } {
  const lower = text.toLowerCase();
  const words = lower.split(/\s+/).filter((w) => w.length > 1);
  const wordCount = words.length;
  const keywordsFound = MEDICAL_KEYWORDS.filter((kw) => lower.includes(kw)).length;

  let score = 0;
  if (wordCount >= 80) score += 45;
  else if (wordCount >= 30) score += 30;
  else if (wordCount >= 10) score += 15;
  score += Math.min(keywordsFound * 5, 35);

  return { score: Math.min(100, score), wordCount, keywordsFound };
}

// ─── Thumbnail Generation ─────────────────────────────────────────────────────

async function toThumbnailBase64(imageBuffer: Buffer, maxWidth = 800): Promise<string> {
  const thumb = await sharp(imageBuffer)
    .resize(maxWidth, Math.floor(maxWidth * 1.5), { fit: "inside", withoutEnlargement: true })
    .jpeg({ quality: 88 })
    .toBuffer();
  return thumb.toString("base64");
}

async function makePlaceholderThumbnail(pageNumber: number): Promise<string> {
  const svg = `<svg width="300" height="420" xmlns="http://www.w3.org/2000/svg">
    <rect width="300" height="420" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1.5"/>
    <text x="150" y="200" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#94a3b8">Página ${pageNumber}</text>
    <text x="150" y="220" text-anchor="middle" font-family="sans-serif" font-size="9" fill="#cbd5e1">Processando...</text>
  </svg>`;
  const buf = await sharp(Buffer.from(svg)).jpeg({ quality: 80 }).toBuffer();
  return buf.toString("base64");
}

// ─── LLM Vision ──────────────────────────────────────────────────────────────

async function extractTextWithLLM(imageBase64: string): Promise<string> {
  try {
    const llmResponse = await invokeLLM({
      messages: [
        {
          role: "system" as const,
          content:
            "Você é um especialista em extração de texto de documentos médicos. Extraia TODO o texto visível na imagem, preservando a estrutura original (títulos, campos, valores, parágrafos). Mantenha a formatação com quebras de linha onde apropriado. Retorne apenas o texto extraído, sem comentários adicionais.",
        },
        {
          role: "user" as const,
          content: [
            {
              type: "image_url" as const,
              image_url: { url: `data:image/jpeg;base64,${imageBase64}`, detail: "high" as const },
            },
            { type: "text" as const, text: "Extraia todo o texto deste documento médico." },
          ],
        },
      ],
    });
    const raw = llmResponse?.choices?.[0]?.message?.content;
    return typeof raw === "string" ? raw : "";
  } catch (err) {
    console.error("[classifier] extractTextWithLLM error:", err);
    return "";
  }
}

// ─── Main Analysis ────────────────────────────────────────────────────────────

async function analyzePdf(filePath: string): Promise<AnalyzeResult> {
  const fileBuffer = fs.readFileSync(filePath);

  const [numPages, pageTexts] = await Promise.all([
    getPdfPageCount(fileBuffer),
    extractNativeTextPerPage(fileBuffer),
  ]);

  const pages: PageAnalysis[] = [];

  for (let i = 0; i < numPages; i++) {
    const pageNum = i + 1;
    const nativeText = (pageTexts[i] || "").trim();
    const hasNativeText = nativeText.length > 50;

    // Always render the real page as image for the thumbnail
    const pageImageBuffer = await renderPdfPageToJpeg(fileBuffer, pageNum);

    if (pageImageBuffer) {
      // Generate high-quality thumbnail (800px wide for clear reading)
      const thumbnailBase64 = await toThumbnailBase64(pageImageBuffer, 800);

      let classification: PageClassification;
      let score: number;
      let details: PageAnalysis["details"];

      // Classification is now done by the user — default to indefinido
      classification = "indefinido";
      score = 0;
      details = { hasNativeText, isScanned: !hasNativeText };

      pages.push({ pageNumber: pageNum, classification, score, thumbnailBase64, details });
    } else {
      // Render failed: use placeholder, classify by text if available
      const thumbnailBase64 = await makePlaceholderThumbnail(pageNum);
      const { score, wordCount, keywordsFound } = hasNativeText ? scoreText(nativeText) : { score: 60, wordCount: 0, keywordsFound: 0 };
      pages.push({
        pageNumber: pageNum,
        classification: hasNativeText && score >= 30 ? "laudo" : "laudo",
        score,
        thumbnailBase64,
        details: { wordCount, keywordsFound, hasNativeText, isScanned: !hasNativeText },
      });
    }
  }

  return { totalPages: numPages, pages };
}

async function analyzeImage(filePath: string): Promise<AnalyzeResult> {
  const imageBuffer = fs.readFileSync(filePath);
  const thumbnailBase64 = await toThumbnailBase64(imageBuffer, 800);
  // Classification is now done by the user — default to indefinido
  return {
    totalPages: 1,
    pages: [
      {
        pageNumber: 1,
        classification: "indefinido",
        score: 0,
        thumbnailBase64,
        details: { isScanned: false },
      },
    ],
  };
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function analyzeDocument(filePath: string): Promise<AnalyzeResult> {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === ".pdf") return analyzePdf(filePath);
  if ([".jpg", ".jpeg", ".png"].includes(ext)) return analyzeImage(filePath);
  throw new Error(`Tipo de arquivo não suportado: ${ext}`);
}

export async function extractTextFromPages(
  filePath: string,
  selectedPageNumbers: number[],
  onPageProgress?: (pageNum: number, status: "processing" | "done" | "error") => Promise<void>
): Promise<OcrResult> {
  const ext = path.extname(filePath).toLowerCase();
  const results: OcrPage[] = [];

  console.log(`[OCR] Iniciando — arquivo: ${path.basename(filePath)}, páginas selecionadas: [${selectedPageNumbers.join(", ")}]`);

  if (ext === ".pdf") {
    const fileBuffer = fs.readFileSync(filePath);

    for (const pageNum of selectedPageNumbers) {
      console.log(`[OCR] Processando página ${pageNum}...`);
      if (onPageProgress) await onPageProgress(pageNum, "processing");

      try {
        // 1ª tentativa: pdfjs-dist — extrai texto nativo da página (100% Node.js)
        const nativeText = await extractNativeTextSinglePage(fileBuffer, pageNum);
        console.log(`[OCR] Página ${pageNum} — texto nativo (pdfjs): ${nativeText.length} chars`);

        if (nativeText.length > 50) {
          results.push({ pageNumber: pageNum, text: nativeText, charCount: nativeText.length });
          console.log(`[OCR] Página ${pageNum} — OK via pdfjs texto nativo`);
        } else {
          // 2ª tentativa: PDF escaneado — renderizar com pdfjs+canvas e enviar ao LLM
          console.log(`[OCR] Página ${pageNum} — texto insuficiente, renderizando via pdfjs+canvas...`);
          const pageImageBuffer = await renderPdfPageToJpeg(fileBuffer, pageNum);

          if (pageImageBuffer) {
            console.log(`[OCR] Página ${pageNum} — imagem: ${pageImageBuffer.length} bytes, enviando ao LLM...`);
            const resizedBuffer = await sharp(pageImageBuffer)
              .resize(1400, 1960, { fit: "inside", withoutEnlargement: true })
              .jpeg({ quality: 88 })
              .toBuffer();
            const imageBase64 = resizedBuffer.toString("base64");
            const extractedText = await extractTextWithLLM(imageBase64);
            console.log(`[OCR] Página ${pageNum} — LLM retornou: ${extractedText.length} chars`);
            results.push({ pageNumber: pageNum, text: extractedText, charCount: extractedText.length });
          } else {
            console.error(`[OCR] Página ${pageNum} — FALHA: renderização não gerou imagem`);
            results.push({ pageNumber: pageNum, text: "", charCount: 0 });
          }
        }
        if (onPageProgress) await onPageProgress(pageNum, "done");
      } catch (pageErr) {
        console.error(`[OCR] Página ${pageNum} — ERRO:`, pageErr);
        if (onPageProgress) await onPageProgress(pageNum, "error");
        results.push({ pageNumber: pageNum, text: "", charCount: 0 });
      }
    }
  } else if ([".jpg", ".jpeg", ".png"].includes(ext)) {
    console.log(`[OCR] Processando imagem diretamente via LLM...`);
    if (onPageProgress) await onPageProgress(1, "processing");
    try {
      const imageBuffer = fs.readFileSync(filePath);
      const resizedBuffer = await sharp(imageBuffer)
        .resize(1400, 1960, { fit: "inside", withoutEnlargement: true })
        .jpeg({ quality: 88 })
        .toBuffer();
      const imageBase64 = resizedBuffer.toString("base64");
      const extractedText = await extractTextWithLLM(imageBase64);
      console.log(`[OCR] Imagem — LLM retornou: ${extractedText.length} chars`);
      results.push({ pageNumber: 1, text: extractedText, charCount: extractedText.length });
      if (onPageProgress) await onPageProgress(1, "done");
    } catch (imgErr) {
      console.error(`[OCR] Imagem — ERRO:`, imgErr);
      if (onPageProgress) await onPageProgress(1, "error");
      results.push({ pageNumber: 1, text: "", charCount: 0 });
    }
  }

  const totalChars = results.reduce((s, p) => s + p.charCount, 0);
  console.log(`[OCR] Concluído — ${results.length} página(s), total: ${totalChars} chars`);
  return { pages: results };
}
