/**
 * Medical Document Page Classifier - Node.js Implementation v1.4
 *
 * Estratégia híbrida para máxima performance em produção:
 * - PDFs com texto nativo: extração direta com pdf-parse (rápido, sem LLM)
 * - PDFs escaneados: renderização local com pdfjs + @napi-rs/canvas para thumbnails,
 *   mas OCR via LLM com imagem redimensionada (max 1200px)
 * - JPEG/JPG: LLM vision diretamente
 * - Timeout agressivo por página para evitar Service Unavailable
 */

import * as pdfParseModule from "pdf-parse";
const pdfParse = (pdfParseModule as any).default ?? pdfParseModule;

import sharp from "sharp";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { execFile } from "child_process";
import { promisify } from "util";
import { invokeLLM } from "./_core/llm";
const execFileAsync = promisify(execFile);

// ─── Types ───────────────────────────────────────────────────────────────────

export type PageClassification = "laudo" | "imagem" | "indefinido";

export interface PageAnalysis {
  pageNumber: number;
  classification: PageClassification;
  score: number;
  thumbnailBase64: string;
  details: {
    wordCount?: number;
    keywordsFound?: number;
    hasNativeText?: boolean;
    isScanned?: boolean;
  };
}

export interface AnalyzeResult {
  totalPages: number;
  pages: PageAnalysis[];
}

export interface OcrPage {
  pageNumber: number;
  text: string;
  charCount: number;
}

export interface OcrResult {
  pages: OcrPage[];
}

// ─── Medical Keywords ────────────────────────────────────────────────────────

const MEDICAL_KEYWORDS = [
  "paciente", "nome", "data", "exame", "laudo", "resultado", "conclusão",
  "achados", "diagnóstico", "médico", "crm", "hospital", "clínica",
  "laboratório", "hemograma", "tomografia", "ultrassom", "ressonância",
  "radiografia", "dosagem", "valor", "referência", "normal", "alterado",
  "positivo", "negativo", "ausente", "presente", "observação",
  "impressão", "descrição", "técnica", "indicação", "solicitante",
  "assinatura", "carimbo", "registro", "prontuário", "cpf", "rg",
  "idade", "sexo", "masculino", "feminino", "nascimento",
  "mg/dl", "g/dl", "u/l", "mm/h", "mmhg", "ml", "mg", "kg",
  "hemácia", "leucócito", "plaqueta", "glicose", "creatinina",
  "colesterol", "triglicérides", "proteína", "bilirrubina",
  "tsh", "t4", "psa", "pcr", "vhs", "hba1c", "interpretação",
  "informação clínica", "técnica do exame", "impressão diagnóstica",
  "relatório", "nasc", "realizante", "pi-rads",
];

// ─── PDF Rendering (poppler pdftoppm — robust for all PDF types) ─────────────────────────

/**
 * Render a single PDF page to JPEG buffer using pdftoppm (poppler-utils).
 * Much more robust than pdfjs-dist for PDFs with embedded fonts, complex layouts,
 * and documents generated by hospital systems (e.g., MRI/CT reports).
 */
async function renderPdfPageToJpeg(
  pdfBuffer: Buffer,
  pageNumber: number
): Promise<Buffer | null> {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "medsuite-"));
  const tmpPdf = path.join(tmpDir, "input.pdf");
  const outPrefix = path.join(tmpDir, "page");

  try {
    fs.writeFileSync(tmpPdf, pdfBuffer);

    // pdftoppm: -jpeg -r 150 (150 DPI gives ~1200px for A4) -f/-l select page range
    await execFileAsync("pdftoppm", [
      "-jpeg",
      "-r", "150",
      "-f", String(pageNumber),
      "-l", String(pageNumber),
      tmpPdf,
      outPrefix,
    ]);

    // pdftoppm outputs: outPrefix-000001.jpg (zero-padded)
    const files = fs.readdirSync(tmpDir).filter((f) => f.endsWith(".jpg") || f.endsWith(".jpeg") || f.endsWith(".ppm"));
    if (files.length === 0) return null;

    const rendered = fs.readFileSync(path.join(tmpDir, files[0]));
    return rendered;
  } catch (err) {
    console.error(`[classifier] renderPdfPageToJpeg (pdftoppm) error (page ${pageNumber}):`, err);
    return null;
  } finally {
    // Clean up temp files
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch {}
  }
}

/**
 * Get number of pages in a PDF buffer using pdftoppm.
 */
async function getPdfPageCount(pdfBuffer: Buffer): Promise<number> {
  try {
    const pdfjsLib = await import("pdfjs-dist/legacy/build/pdf.mjs");
    const uint8 = new Uint8Array(pdfBuffer);
    const loadingTask = pdfjsLib.getDocument({ data: uint8, verbosity: 0 });
    const pdf = await loadingTask.promise;
    return pdf.numPages;
  } catch {
    try {
      const data = await pdfParse(pdfBuffer);
      return data.numpages || 1;
    } catch {
      return 1;
    }
  }
}

// ─── Text Extraction ─────────────────────────────────────────────────────────

/**
 * Extract native text from PDF per page using pdfjs-dist.
 * More reliable than pdf-parse pagerender for PDFs generated by iTextSharp, Zenite, etc.
 */
async function extractNativeTextPerPage(pdfBuffer: Buffer): Promise<string[]> {
  const pageTexts: string[] = [];
  try {
    const pdfjsLib = await import("pdfjs-dist/legacy/build/pdf.mjs");
    const uint8 = new Uint8Array(pdfBuffer);
    const loadingTask = pdfjsLib.getDocument({ data: uint8, verbosity: 0 });
    const pdf = await loadingTask.promise;

    for (let i = 1; i <= pdf.numPages; i++) {
      try {
        const page = await pdf.getPage(i);
        const textContent = await page.getTextContent();
        const text = textContent.items
          .map((item: any) => item.str)
          .join(" ")
          .trim();
        pageTexts[i - 1] = text;
      } catch {
        pageTexts[i - 1] = "";
      }
    }
  } catch (err) {
    console.error("[classifier] extractNativeTextPerPage error:", err);
    // Fallback: use pdf-parse for total text, split evenly
    try {
      const data = await pdfParse(pdfBuffer);
      const numPages = data.numpages || 1;
      const chunkSize = Math.ceil(data.text.length / numPages);
      for (let i = 0; i < numPages; i++) {
        pageTexts[i] = data.text.substring(i * chunkSize, (i + 1) * chunkSize);
      }
    } catch {
      pageTexts[0] = "";
    }
  }
  return pageTexts;
}

// ─── Scoring ─────────────────────────────────────────────────────────────────

function scoreText(text: string): { score: number; wordCount: number; keywordsFound: number } {
  const lower = text.toLowerCase();
  const words = lower.split(/\s+/).filter((w) => w.length > 1);
  const wordCount = words.length;
  const keywordsFound = MEDICAL_KEYWORDS.filter((kw) => lower.includes(kw)).length;

  let score = 0;
  if (wordCount >= 80) score += 45;
  else if (wordCount >= 30) score += 30;
  else if (wordCount >= 10) score += 15;
  score += Math.min(keywordsFound * 5, 35);

  return { score: Math.min(100, score), wordCount, keywordsFound };
}

// ─── Thumbnail Generation ─────────────────────────────────────────────────────

async function toThumbnailBase64(imageBuffer: Buffer, maxWidth = 800): Promise<string> {
  const thumb = await sharp(imageBuffer)
    .resize(maxWidth, Math.floor(maxWidth * 1.5), { fit: "inside", withoutEnlargement: true })
    .jpeg({ quality: 88 })
    .toBuffer();
  return thumb.toString("base64");
}

async function makePlaceholderThumbnail(pageNumber: number): Promise<string> {
  const svg = `<svg width="300" height="420" xmlns="http://www.w3.org/2000/svg">
    <rect width="300" height="420" fill="#f8fafc" stroke="#e2e8f0" stroke-width="1.5"/>
    <text x="150" y="200" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#94a3b8">Página ${pageNumber}</text>
    <text x="150" y="220" text-anchor="middle" font-family="sans-serif" font-size="9" fill="#cbd5e1">Processando...</text>
  </svg>`;
  const buf = await sharp(Buffer.from(svg)).jpeg({ quality: 80 }).toBuffer();
  return buf.toString("base64");
}

// ─── LLM Vision ──────────────────────────────────────────────────────────────

async function classifyImageWithLLM(
  imageBase64: string
): Promise<{ classification: PageClassification; score: number }> {
  try {
    const llmResponse = await invokeLLM({
      messages: [
        {
          role: "system" as const,
          content:
            'Você é um classificador de documentos médicos. Analise a imagem e responda APENAS com JSON: {"type": "laudo", "score": 85} ou {"type": "imagem", "score": 20}. "laudo" = documento com texto de relatório/laudo médico. "imagem" = imagem de diagnóstico (tomografia, ultrassom, raio-x, ressonância sem texto predominante). "score" = confiança 0-100.',
        },
        {
          role: "user" as const,
          content: [
            {
              type: "image_url" as const,
              image_url: { url: `data:image/jpeg;base64,${imageBase64}`, detail: "low" as const },
            },
            { type: "text" as const, text: "Classifique este documento médico." },
          ],
        },
      ],
      response_format: {
        type: "json_schema",
        json_schema: {
          name: "classification",
          strict: true,
          schema: {
            type: "object",
            properties: {
              type: { type: "string", enum: ["laudo", "imagem"] },
              score: { type: "number" },
            },
            required: ["type", "score"],
            additionalProperties: false,
          },
        },
      },
    });

    const raw = llmResponse?.choices?.[0]?.message?.content;
    if (typeof raw === "string") {
      const parsed = JSON.parse(raw);
      return {
        classification: parsed.type as PageClassification,
        score: Math.min(100, Math.max(0, parsed.score ?? 50)),
      };
    }
  } catch (err) {
    console.error("[classifier] classifyImageWithLLM error:", err);
  }
  return { classification: "laudo", score: 60 };
}

async function extractTextWithLLM(imageBase64: string): Promise<string> {
  try {
    const llmResponse = await invokeLLM({
      messages: [
        {
          role: "system" as const,
          content:
            "Você é um especialista em extração de texto de documentos médicos. Extraia TODO o texto visível na imagem, preservando a estrutura original (títulos, campos, valores, parágrafos). Mantenha a formatação com quebras de linha onde apropriado. Retorne apenas o texto extraído, sem comentários adicionais.",
        },
        {
          role: "user" as const,
          content: [
            {
              type: "image_url" as const,
              image_url: { url: `data:image/jpeg;base64,${imageBase64}`, detail: "high" as const },
            },
            { type: "text" as const, text: "Extraia todo o texto deste laudo médico." },
          ],
        },
      ],
    });
    const raw = llmResponse?.choices?.[0]?.message?.content;
    return typeof raw === "string" ? raw : "";
  } catch (err) {
    console.error("[classifier] extractTextWithLLM error:", err);
    return "";
  }
}

// ─── Main Analysis ────────────────────────────────────────────────────────────

async function analyzePdf(filePath: string): Promise<AnalyzeResult> {
  const fileBuffer = fs.readFileSync(filePath);

  const [numPages, pageTexts] = await Promise.all([
    getPdfPageCount(fileBuffer),
    extractNativeTextPerPage(fileBuffer),
  ]);

  const pages: PageAnalysis[] = [];

  for (let i = 0; i < numPages; i++) {
    const pageNum = i + 1;
    const nativeText = (pageTexts[i] || "").trim();
    const hasNativeText = nativeText.length > 50;

    // Always render the real page as image for the thumbnail
    // This ensures the user sees the actual document content, not a text preview
    const pageImageBuffer = await renderPdfPageToJpeg(fileBuffer, pageNum);

    if (pageImageBuffer) {
      // Generate high-quality thumbnail (800px wide for clear reading)
      const thumbnailBase64 = await toThumbnailBase64(pageImageBuffer, 800);

      let classification: PageClassification;
      let score: number;
      let details: PageAnalysis["details"];

      if (hasNativeText) {
        // Native-text PDF: classify by text scoring (fast, no LLM needed)
        const scored = scoreText(nativeText);
        classification = scored.score >= 30 ? "laudo" : "imagem";
        score = scored.score;
        details = { wordCount: scored.wordCount, keywordsFound: scored.keywordsFound, hasNativeText: true, isScanned: false };
      } else {
        // Scanned PDF: classify by LLM vision
        const llmResult = await classifyImageWithLLM(thumbnailBase64);
        classification = llmResult.classification;
        score = llmResult.score;
        details = { hasNativeText: false, isScanned: true };
      }

      pages.push({ pageNumber: pageNum, classification, score, thumbnailBase64, details });
    } else {
      // Render failed: use placeholder, classify by text if available
      const thumbnailBase64 = await makePlaceholderThumbnail(pageNum);
      const { score, wordCount, keywordsFound } = hasNativeText ? scoreText(nativeText) : { score: 60, wordCount: 0, keywordsFound: 0 };
      pages.push({
        pageNumber: pageNum,
        classification: hasNativeText && score >= 30 ? "laudo" : "laudo",
        score,
        thumbnailBase64,
        details: { wordCount, keywordsFound, hasNativeText, isScanned: !hasNativeText },
      });
    }
  }

  return { totalPages: numPages, pages };
}

async function analyzeImage(filePath: string): Promise<AnalyzeResult> {
  const imageBuffer = fs.readFileSync(filePath);
  const thumbnailBase64 = await toThumbnailBase64(imageBuffer, 800);
  const { classification, score } = await classifyImageWithLLM(thumbnailBase64);

  return {
    totalPages: 1,
    pages: [
      {
        pageNumber: 1,
        classification,
        score,
        thumbnailBase64,
        details: { isScanned: false },
      },
    ],
  };
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function analyzeDocument(filePath: string): Promise<AnalyzeResult> {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === ".pdf") return analyzePdf(filePath);
  if ([".jpg", ".jpeg", ".png"].includes(ext)) return analyzeImage(filePath);
  throw new Error(`Tipo de arquivo não suportado: ${ext}`);
}

export async function extractTextFromPages(
  filePath: string,
  selectedPageNumbers: number[]
): Promise<OcrResult> {
  const ext = path.extname(filePath).toLowerCase();
  const results: OcrPage[] = [];

  if (ext === ".pdf") {
    const fileBuffer = fs.readFileSync(filePath);
    const pageTexts = await extractNativeTextPerPage(fileBuffer);

    for (const pageNum of selectedPageNumbers) {
      const nativeText = (pageTexts[pageNum - 1] || "").trim();

      if (nativeText.length > 50) {
        results.push({ pageNumber: pageNum, text: nativeText, charCount: nativeText.length });
      } else {
        // Scanned page: render at moderate resolution for LLM OCR
        const pageImageBuffer = await renderPdfPageToJpeg(fileBuffer, pageNum);

        if (pageImageBuffer) {
          // Resize to max 1400px wide for LLM high-detail mode (good quality, manageable size)
          const resizedBuffer = await sharp(pageImageBuffer)
            .resize(1400, 1960, { fit: "inside", withoutEnlargement: true })
            .jpeg({ quality: 88 })
            .toBuffer();
          const imageBase64 = resizedBuffer.toString("base64");
          const extractedText = await extractTextWithLLM(imageBase64);
          results.push({ pageNumber: pageNum, text: extractedText, charCount: extractedText.length });
        } else {
          results.push({ pageNumber: pageNum, text: "", charCount: 0 });
        }
      }
    }
  } else if ([".jpg", ".jpeg", ".png"].includes(ext)) {
    const imageBuffer = fs.readFileSync(filePath);
    const resizedBuffer = await sharp(imageBuffer)
      .resize(1400, 1960, { fit: "inside", withoutEnlargement: true })
      .jpeg({ quality: 88 })
      .toBuffer();
    const imageBase64 = resizedBuffer.toString("base64");
    const extractedText = await extractTextWithLLM(imageBase64);
    results.push({ pageNumber: 1, text: extractedText, charCount: extractedText.length });
  }

  return { pages: results };
}
